### ISSUE TITLE
Find element with xpath failed

### ISSUE THREAD

**Issue by WeiweiCaiAcpt** [FlaUI/FlaUI.WebDriver#107] opened 2024-10-30 08:51 UTC
I want to get the Windows desktop ToolBar element in my UI testing. When using FlaUInspect to capture it and the xpath shows in FlaUInspect is "/Pane/ToolBar".
![image](https://github.com/user-attachments/assets/0a087d66-f3e5-4e9c-a69c-08a1e7a351cd)

But I always get "OpenQA.Selenium.NoSuchElementException: No element found with selector 'xpath' and value '//ToolBar'" exception when using driver.FindElementByXPath() method. 

Below are the code that we have tried, but non of them are working.

```
 var toolbar =  driver.FindElementByXPath("/Pane/ToolBar");
 var toolbar =  driver.FindElementByXPath("//Pane/ToolBar");
 var toolbar =  driver.FindElementByXPath("//ToolBar");
```

Are there anything missing when passing xpath to the method?

**Comment by bmarroquin** [comment] 2024-10-30 20:55
How are you initializing the driver? Are you using the "Root" app like in https://github.com/FlaUI/FlaUI.WebDriver/issues/59?

**Comment by WeiweiCaiAcpt** [comment] 2024-10-31 01:03
@bmarroquin Thanks for looking into this issue.

Yes, I use the "Root" app to initialize the driver. I use the same code as this file to initialize the driver: [src/FlaUI.WebDriver.UITests/TestUtil/FlaUIAppiumDriverOptions.cs](https://github.com/FlaUI/FlaUI.WebDriver/blob/main/src/FlaUI.WebDriver.UITests/TestUtil/FlaUIAppiumDriverOptions.cs)

In https://github.com/FlaUI/FlaUI.WebDriver/issues/59, I see it has been completed on Aug 26. And the [FlaUI.WebDriver.exe](https://github.com/FlaUI/FlaUI.WebDriver/releases/download/v0.3.1/FlaUI.WebDriver.exe) I used is v0.3.1, which is released on Sep 30. So I think it should be supported to find the desktop element.

**Comment by aristotelos** [comment] 2024-11-05 15:04
This was merged in https://github.com/FlaUI/FlaUI.WebDriver/commit/666feb62d05a147439b20976e5c2a2084ef55761 which is tag v0.3.2. Could you try updating?

**Closed by aristotelos** 2024-11-05 15:04 UTC

**Comment by WeiweiCaiAcpt** [comment] 2024-11-11 05:12
> This was merged in [666feb6](https://github.com/FlaUI/FlaUI.WebDriver/commit/666feb62d05a147439b20976e5c2a2084ef55761) which is tag v0.3.2. Could you try updating?

@aristotelos  Thanks for looking into this issue.

I have get the latest version of code and try the FindElement_ByXPath_ReturnsElement() test method in [FindElementsTests.cs](https://github.com/FlaUI/FlaUI.WebDriver/blob/666feb62d05a147439b20976e5c2a2084ef55761/src/FlaUI.WebDriver.UITests/FindElementsTests.cs). 

By default, it can find the element when using "//Text" as XPath for the WPF Test Application. And if I tried to get the Taskbar (the parent of Toolbar) with "//Pane" as XPath, the test method can pass.

But if I modify the XPath to "//ToolBar", the test method will failed with error "No element found with selector 'xpath' and value '//ToolBar'". (Also tried with "//Pane/ToolBar" as XPath.)

The same result in my UI Test case.

**Background of test scenario:**
We want to minimize the desktop application window. Then will maximize it from toolbar to restore its window.

**Comment by aristotelos** [comment] 2024-11-11 08:11
Sometimes Windows UI Automation seems to not find elements from the root, but only from a parent. Could you try first locating the pane, and then finding elements from the pane?

**Comment by WeiweiCaiAcpt** [comment] 2024-11-12 08:30
> Sometimes Windows UI Automation seems to not find elements from the root, but only from a parent. Could you try first locating the pane, and then finding elements from the pane?

Yes, I tried with find pane first, then use pane.FindElement(By.Name("")) or pane.FindElement(By.XPath("")) to try find its child element. But unfortunately, both of them are not work.

**Comment by aristotelos** [comment] 2024-11-22 12:02
@WeiweiCaiAcpt I cannot reproduce what you see, in my inspector the set of app buttons is not a ToolBar but a Pane with automation ID "TaskbarFrame" (probably because I run another version of Windows). The following code works to get it:

```
[Test]
public void FindElement_TaskbarFrame_ReturnsElement()
{
    var driverOptions = FlaUIDriverOptions.RootApp();
    using var driver = new RemoteWebDriver(WebDriverFixture.WebDriverUrl, driverOptions);

    var element = driver.FindElement(By.Id("TaskbarFrame"));

    Assert.That(element, Is.Not.Null);
}
```

**Comment by WeiweiCaiAcpt** [comment] 2024-11-25 01:46
Are you using Windows 11, right? I tried with Windows 11 24H2, it also shows "TaskbarFrame".

The issue I see in original post is on Windows 10 22H2. So it seems that the Taskbar have different Id on different Windows version.
